class Utils{
  static const List<String> titleList = <String>[
  'Master',
  'Mr',
  'Miss',
  'Mrs',
  'Sir',
  'Madam',
  'Dame',
  'Esq',
  'Honorable',
  'Dr',
  'Prof',
  'Eng',
  'Barr',
  'Gov',
  'Pst',
  'Rev',
  'Fr',
  'Br',
  'Sis',
  'Elder',
  'Gen',
  'Major.Gen',
  'Brig.Gen',
  'Captain',
  'Commander',
  'Col',
  'Lt',
  'Sgt',
  'Adm',
  'v.Adm'
];

  



  static const CarMake ={'Acura':'Ac',
    'Ashok':'Ash',
    'Audi':'Aud',
    'Bentley Continental':'Bent',
    'BMW':'Bmw',
    'Buick':'Bui',
    'Cadillac':'Cad',
    'Chevrolet':'Chev',
    'Chrysler':'Chr',
    'Citroen':'Cit',
    'Daihatsu':'Dai',
    'Dodge':'Dod',
    'Fiat':'Fia',
    'Ford':'For',
    'Foton':'Fot',
    'GAC':'Gac',
    'Geely':'Gee',
    'GMC':'Gmc',
    'Haima':'Hai',
    'Honda':'Hon',
    'Hummer':'Hum',
    'Hyundai':'Hyu',
    'Infiniti':'Inf',
    'Innoson':'Inn',
    'Isuzu':'Isu',
    'Jaguar':'Jag',
    'Jeep':'Jee',
    'JMC':'Jmc',
    'Kia':'Kia',
    'Land Rover':'Rov',
    'Lexus':'Lex',
    'Lincoln':'Lin',
    'Mazda':'Maz',
    'Mercedes Benz':'Ben',
    'Mercury':'Mer',
    'MG':'Mg',
    'Mini':'Min',
    'Mitsubishi':'Mit',
    'Nissan':'Nis',
    'Opel':'Ope',
    'Peugeot':'Peu',
    'Pontiac':'Pon',
    'Porsche':'Por',
    'Range Rover':'Ran',
    'Renauly':'Ren',
    'Rolls-Royce':'Roll',
    'Rover':'Rov',
    'Saturn':'Sat',
    'Scion':'Sci',
    'Seat':'Sea',
    'Skoda':'Sko',
    'Ssangyong':'Ssa',
    'Stallion':'Sta',
    'Subaru':'Sub',
    'Suzuki':'Suz',
    'Suzuki Evey Wagon':'SuzE',
    'Toyota':'Toy',
    'Volkswagen':'Volk',
    'Volvo':'Volv'};

  static var CarModel ={
    'Legend':'Ac',
    'Mdx':'Ac',
    'Rdx':'Ac',
    'Tl':'Ac',
    'Tlx':'Ac',
    'Tsx':'Ac',
    'Zdx':'Ac',

    'Leyland':'Ash',

    'A4':'Aud',
    'A5':'Aud',
    'A6':'Aud',
    'Q7':'Aud',
    'Tt':'Aud',

    'Continental':'Bent',

    '1 Series':'Bmw',
    'E 81':'Bmw',
    'E 82':'Bmw',
    'E 87':'Bmw',
    'E 88':'Bmw',
    'F 20':'Bmw',
    'F 21':'Bmw',
    'F 40':'Bmw',
    'F 52':'Bmw',
    '3 Series':'Bmw',
    'E 21':'Bmw',
    'E 30':'Bmw',
    'E 36':'Bmw',
    'E 46':'Bmw',
    'E 90':'Bmw',
    'E 91':'Bmw',
    'E 92':'Bmw',
    'E 93':'Bmw',
    'F 30':'Bmw',
    'F 31':'Bmw',
    'F 34':'Bmw',
    'F 35':'Bmw',
    'G 20':'Bmw',
    'G 21':'Bmw',
    'G 28':'Bmw',
    '318i':'Bmw',
    '320i':'Bmw',
    '325i':'Bmw',
    '330i':'Bmw',
    '330XI':'Bmw',
    '5 Series':'Bmw',
    'E 12':'Bmw',
    'E 28':'Bmw',
    'E 34':'Bmw',
    'E 39':'Bmw',
    'E 60':'Bmw',
    'E 61':'Bmw',
    'F 10':'Bmw',
    'F 11':'Bmw',
    'F 07':'Bmw',
    'F 18':'Bmw',
    'G 30':'Bmw',
    'G 31':'Bmw',
    'G 38':'Bmw',
    '7 Series':'Bmw',
    'G 11':'Bmw',
    'G 12':'Bmw',
    'F 01':'Bmw',
    'F 02':'Bmw',
    'F 03':'Bmw',
    'E 65':'Bmw',
    'E 66':'Bmw',
    'E 67':'Bmw',
    'E 38':'Bmw',
    'E 32':'Bmw',
    'E 23':'Bmw',
    'ALPINA':'Bmw',
    'X3':'Bmw',
    'X5':'Bmw',
    'X6':'Bmw',

    'Enclave':'Bui',
    'LACROSSE':'Bui',

    'Cts':'Cad',
    'Escalade':'Cad',
    'Srx':'Cad',
    'STS':'Cad',

    'Avalanche':'Chev',
    'Aveo':'Chev',
    'Camaro':'Chev',
    'Cobalt':'Chev',
    'Cruze':'Chev',
    'epica':'Chev',
    'Equinox':'Chev',
    'Express Cargo':'Chev',
    'GM HOLDEN':'Chev',
    'Malibu':'Chev',
    'N300':'Chev',
    'Nubira':'Chev',
    'Optra':'Chev',
    'TRACKER':'Chev',
    'Trailblazer':'Chev',
    'Traverse':'Chev',
    'Uplander':'Chev',
    'Venture':'Chev',

    '300':'Chr',
    'Pacifica':'Chr',
    'Pt Cruiser':'Chr',
    'S 200':'Chr',
    'Sebring':'Chr',
    'Town & Country':'Chr',

    'BERLINGO':'Cit',

    'MOVE':'Dai',
    'Avenger':'Dod',
    'Caliber':'Dod',
    'Caravan':'Dod',
    'Challenger':'Dod',
    'Charger':'Dod',
    'Durango':'Dod',
    'Journey':'Dod',
    'Magnum':'Dod',
    'Minivan':'Dod',
    'Ram':'Dod',
    'Ram Promaster':'Dod',
    'Sprinter':'Dod',

    'Ducato':'Fia',
    'FULLBACK':'Fia',
    'TIBO':'Fia',

    'E-350':'For',
    'E-Series':'For',
    'Econoline':'For',
    'Ecosport':'For',
    'Edge':'For',
    'Escape':'For',
    'Everest':'For',
    'Expedition':'For',
    'Explorer':'For',
    'Explorer Ford Sport Trac':'For',
    'F-150':'For',
    'Flex':'For',
    'Focus':'For',
    'Freestyle':'For',
    'Fusion':'For',
    'Galaxy':'For',
    'Mondeo':'For',
    'Mustang':'For',
    'Ranger':'For',
    'SMax':'For',
    'Taurus':'For',
    'Transit':'For',
    'Windstar':'For',

    'VIEW CS2':'Fot',

    'GA4':'Gac',
    'GA3-S':'Gac',
    'GS4':'Gac',
    'GS5':'Gac',

    'CK':'Gee',

    'Acadia':'Gmc',
    'SAVANA':'Gmc',
    'Sierra':'Gmc',


    '3':'Hai',

    'Element':'Hon',
    'Accord':'Hon',
    'Accord Crosstour':'Hon',
    'City':'Hon',
    'Civic':'Hon',
    'Cr-V':'Hon',
    'CR-V':'Hon',
    'Crv':'Hon',
    'Hr-V':'Hon',
    'Odyssey':'Hon',
    'Passport':'Hon',
    'Pilot':'Hon',
    'Ridgeline':'Hon',
    'Shuttle':'Hon',
    'Stream':'Hon',

    'H1':'Hum',
    'H3':'Hum',

    'Accent':'Hyu',
    'Azera':'Hyu',
    'County':'Hyu',
    'Creta':'Hyu',
    'Elantra':'Hyu',
    'Entourage':'Hyu',
    'Genesis':'Hyu',
    'GRAND i10 XCENT':'Hyu',
    'HD 45':'Hyu',
    'i10':'Hyu',
    'Ix35':'Hyu',
    'Santa Fe':'Hyu',
    'Santamo':'Hyu',
    'Sonata':'Hyu',
    'Tiburon':'Hyu',
    'Trajet':'Hyu',
    'Tucson':'Hyu',
    'Veloster':'Hyu',
    'Veracruz':'Hyu',
    'XG30':'Hyu',

    'Fx':'Inf',
    'Fx 35':'Inf',
    'Fx 37':'Inf',
    'Fx 45':'Inf',
    'Fx 50':'Inf',
    'G':'Inf',
    'G35':'Inf',
    'G35X':'Inf',
    'G37':'Inf',
    'M':'Inf',
    'M 30':'Inf',
    'M 35':'Inf',
    'M 45':'Inf',
    'Qx':'Inf',
    'QX4':'Inf',
    'QX56':'Inf',

    'IVMG5':'Inn',

    'Axiom':'Isu',
    'NQR':'Isu',
    'Rodeo':'Isu',

    'S-Type':'Jag',
    'X-Tyoe':'Jag',
    'XE':'Jag',
    'Xj':'Jag',
    'Xk':'Jag',

    'Cherokee':'Jee',
    'Commander':'Jee',
    'Compass':'Jee',
    'Grand Cherokee':'Jee',
    'Grand Cherokee Luxury Brand':'Jee',
    'Grand Cherokee Premium Brand':'Jee',
    'Grand Cherokee SRT':'Jee',
    'Liberty':'Jee',
    'Wrangler':'Jee',

    'NEW CARYING LIGHT DUTY':'Jmc',

    'Amanti':'Kia',
    'Carens':'Kia',
    'Carniva':'Kia',
    'Cerato':'Kia',
    'Joice':'Kia',
    'K3000':'Kia',
    'Mohave':'Kia',
    'Opirius':'Kia',
    'Optima':'Kia',
    'Picanto':'Kia',
    'Quoris':'Kia',
    'Rio':'Kia',
    'Sedona':'Kia',
    'Sorento':'Kia',
    'Soul':'Kia',
    'Spectra':'Kia',
    'VENGA':'Kia',

    'Discovery':'Rov',
    'Freelander':'Rov',
    'HSE':'Rov',
    'Lr3':'Rov',
    'Lr2':'Rov',
    'Lr4':'Rov',
    'Range Rover':'Rov',
    'Range Rover Evoque':'Rov',
    'Range Rover HSE':'Rov',
    'Range Rover Sport':'Rov',
    'Range Rover Velar':'Rov',
    'Range Rover Vogue':'Rov',
    'HSE SPORTS':'Rov',

    'CT 200h':'Lex',
    'Es 300':'Lex',
    'Es 330':'Lex',
    'Es 350':'Lex',
    'Gs 300':'Lex',
    'Gs 330':'Lex',
    'Gs 350':'Lex',
    'Gs 430':'Lex',
    'GX 460':'Lex',
    'GX 470':'Lex',
    'IS 200T':'Lex',
    'IS 250':'Lex',
    'IS 350':'Lex',
    'Ls':'Lex',
    'LS460':'Lex',
    'Lx':'Lex',
    'Lx 470':'Lex',
    'Lx 570':'Lex',
    'NX':'Lex',
    'Rx':'Lex',
    'RX 300':'Lex',
    'RX 330':'Lex',
    'Rx 400h':'Lex',

    'Mk6':'Lin',
    'Mkv':'Lin',
    'Mkz':'Lin',
    'Navigator':'Lin',
    'Town Car':'Lin',

    '323':'Maz',
    '5':'Maz',
    '6':'Maz',
    '626':'Maz',
    'Cx-7':'Maz',
    'Cx-9':'Maz',
    'Mazda5':'Maz',
    'Millenia':'Maz',
    'Mpv':'Maz',
    'X-5 Miata':'Maz',
    'Premacy':'Maz',
    'PRIMACY':'Maz',
    'Tribute':'Maz',

    'CLS 350':'Ben',
    'ML 350':'Ben',
    'C 240':'Ben',
    'C 300':'Ben',
    'C-180':'Ben',
    'C 220':'Ben',
    'CLS 500':'Ben',
    'GL 450':'Ben',
    'GL 500':'Ben',
    'A140':'Ben',
    'A160':'Ben',
    'A170':'Ben',
    'A180':'Ben',
    'B150':'Ben',
    'B180':'Ben',
    'C200':'Ben',
    'C 230':'Ben',
    'C 250':'Ben',
    'C-CLASS':'Ben',
    'C180':'Ben',
    'C200':'Ben',
    'C220 Cdi':'Ben',
    'C230':'Ben',
    'C240':'Ben',
    'C250':'Ben',
    'C280':'Ben',
    'C300':'Ben',
    'C320':'Ben',
    'C350':'Ben',
    'C43':'Ben',
    'C63 Amg':'Ben',
    'CI500':'Ben',
    'CLA 250':'Ben',
    'Clk200':'Ben',
    'Cls250':'Ben',
    'Cls500':'Ben',
    'Cls55 Amg':'Ben',
    'Cls550':'Ben',
    'E230':'Ben',
    'E200':'Ben',
    'E240':'Ben',
    'E280':'Ben',
    'E300':'Ben',
    'E320':'Ben',
    'E350':'Ben',
    'E43':'Ben',
    'E430':'Ben',
    'E500':'Ben',
    'E550':'Ben',
    'G class':'Ben',
    'G 320':'Ben',
    'G500':'Ben',
    'G550':'Ben',
    'G63':'Ben',
    'Gl-cLASS':'Ben',
    'GI350':'Ben',
    'GI420':'Ben',
    'GI450':'Ben',
    'GI500':'Ben',
    'GI550':'Ben',
    'GLA250':'Ben',
    'GLC 300':'Ben',
    'GLC43':'Ben',
    'GLE350':'Ben',
    'GLE450':'Ben',
    'GLK350':'Ben',
    'GLK250':'Ben',
    'M-CLASS':'Ben',
    'MI320':'Ben',
    'MI350':'Ben',
    'MI500':'Ben',
    'MI550':'Ben',
    'MI63 Amg':'Ben',
    'R350':'Ben',
    'R500':'Ben',
    'R500 Brabus':'Ben',
    'S320':'Ben',
    'S350':'Ben',
    'S500':'Ben',
    'S550':'Ben',
    'S600':'Ben',
    'Slk230':'Ben',
    'Slk350':'Ben',
    'VIANO':'Ben',
    'Vito':'Ben',
    'W123':'Ben',
    'Trucck':'Ben',
    'E350':'Ben',

    'Villager':'Mer',

    '350s':'Mg',
    '550':'Mg',

    'Cooper':'Min',

    'Attrage':'Mit',
    'BUS':'Mit',
    'Eclipse':'Mit',
    'Endeavor':'Mit',
    'Galant':'Mit',
    'L200':'Mit',
    'L300':'Mit',
    'L400':'Mit',
    'Lancer':'Mit',
    'Montero':'Mit',
    'Outlander':'Mit',
    'Pajero':'Mit',
    'Space gear':'Mit',
    'SpaceStar':'Mit',

    '370z':'Nis',
    'Almera':'Nis',
    'Altima':'Nis',
    'Armada':'Nis',
    'Cefiro':'Nis',
    'Civilian':'Nis',
    'Frontier':'Nis',
    'INFINITY':'Nis',
    'Juke':'Nis',
    'Kicks':'Nis',
    'Maxima':'Nis',
    'Murano':'Nis',
    'Pathfinder':'Nis',
    'Patrol':'Nis',
    'Primera':'Nis',
    'Pulsar':'Nis',
    'Qashqai':'Nis',
    'Quest':'Nis',
    'Rogue':'Nis',
    'Sentra':'Nis',
    'Serena':'Nis',
    'Sunny':'Nis',
    'Teana':'Nis',
    'Tiida':'Nis',
    'Titan':'Nis',
    'Vanette':'Nis',
    'Versa':'Nis',
    'X-Trail':'Nis',
    'Xterra':'Nis',

    'Astra':'Ope',
    'Frontera':'Ope',
    'Signum':'Ope',
    'Vectra':'Ope',
    'Zafira':'Ope',

    '206':'Peu',
    '207':'Peu',
    '301':'Peu',
    '307':'Peu',
    '308':'Peu',
    '406':'Peu',
    '407':'Peu',
    '408':'Peu',
    '508':'Peu',
    '607':'Peu',
    '807':'Peu',
    'Boxer':'Peu',
    'Expert':'Peu',

    'Montana':'Pon',
    'SALOON':'Pon',
    'Torent':'Pon',
    'Vibe':'Pon',

    'Boxster':'Por',
    'Cayenne':'Por',

    'VELAR':'Ran',

    'Duster':'Ren',
    'Espace':'Ren',
    'Laguna':'Ren',
    'Megane':'Ren',
    'Scenic':'Ren',

    'Ghoste':'Roll',

    '600':'Rov',
    '75':'Rov',
    'LAND ROVER':'Rov',

    'AURA':'Sat',
    'Outlook':'Sat',
    'VUE':'Sat',

    'Tc':'Sci',

    'Cordoba':'Sea',

    'Fabia':'Sko',
    'Octavia':'Sko',
    'Superb':'Sko',

    'Actyon':'Ssa',

    'Force':'Sta',

    'Forester':'Sub',
    'Impreza':'Sub',
    'Legacy':'Sub',
    'Outback':'Sub',

    'Aerio':'Suz',
    'Alto':'Suz',
    'BALENO':'Suz',
    'CIAZ':'Suz',
    'Ertiga':'Suz',
    'Esteem':'Suz',
    'Forenza':'Suz',
    'Grand Viatra':'Suz',
    'Jimny':'Suz',
    'Kizashi':'Suz',
    'Swift':'Suz',
    'Sx4':'Suz',
    'Vitara':'Suz',
    'XL-7':'Suz',
    'XL7':'Suz',

   'Every Wagon':'SuzE',

    '4Runner':'Toy',
    'Avalon':'Toy',
    'Avanza':'Toy',
    'Avensis':'Toy',
    'Camry':'Toy',
    'CAMRY(HYBRID)':'Toy',
    'Celica':'Toy',
    'Coaster':'Toy',
    'Corolla':'Toy',
    'Corolla Sport':'Toy',
    'COROLLA VERSO':'Toy',
    'Corona':'Toy',
    'Echo':'Toy',
    'Fj Cruiser':'Toy',
    'Fortuner':'Toy',
    'Harrier':'Toy',
    'HiAce':'Toy',
    'Highlander':'Toy',
    'Hilux':'Toy',
    'ipsum':'Toy',
    'KLUGER(HIGHLANDER)':'Toy',
    'Land Cruiser':'Toy',
    'Land Cruiser Prado':'Toy',
    'Mark II':'Toy',
    'Matrix':'Toy',
    'Picnic':'Toy',
    'Prius':'Toy',
    'Rav4':'Toy',
    'Sequoia':'Toy',
    'Sienna':'Toy',
    'Solara':'Toy',
    'Tacoma':'Toy',
    'Tundra':'Toy',
    'Venza':'Toy',
    'Verso':'Toy',
    'Yaris':'Toy',

    'Amarok':'Volk',
    'Beatle':'Volk',
    'Beetle':'Volk',
    'CC':'Volk',
    'Golf':'Volk',
    'Jetta':'Volk',
    'Passat':'Volk',
    'Polo':'Volk',
    'Sharan':'Volk',
    'Tiguaan':'Volk',
    'Touareg':'Volk',
    'Touran':'Volk',

    'S40':'Volv',
    'S60':'Volv',
    'S80':'Volv',
    'V40':'Volv',
    'V60':'Volv',
    'V70':'Volv',
    'X40':'Volv',
    'XC 60':'Volv',
    'XC 90':'Volv',
  };

 static List extension_descript= [
    { "name":"Excess Buy Back",
      "descript":"Excess Buy Back (EBB) is the waiver of the excess amount incurred in the event of a claim under your Comprehensive Motor insurance policy."
          " This means that your insurance provider would be paying 100% of your claim without any deductions "
    },

    {"name":"SRCC",
      "descript":"SRCC (Strike, Riot and Civil Commotion) Extension provides additional cover for loss or damage directly caused by strikers, riots and civil commotion/unrest."
    },

    {"name":"Flood Extension",
      "descript": "This extends your policy to compensate/indemnify you against loss or damage to your vehicle, as a result of flooding."

    },
    {"name":"Tracking",
      "descript":"Your vehicle will be equipped with a tracking device, which would provide you with the means to tracking the location of your vehicle at any time in Nigeria."

    },
   {
     "name":"Additional Third Party Damage",
     "descript":"This increases the monetary limit of your policy for loss or damage to a third party’s property as a result of the operation of your vehicle."
   },
   {"name":"Increased Personal Effective",
     "descript":"This increases the monetary limit of your policy for loss or damage of personal effects in your vehicle resulting from damage to the vehicle."

   }
  ];


}